# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-03 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, help_text='150x150px', upload_to='media', verbose_name='Ссылка картинки')),
                ('video', models.CharField(max_length=300)),
            ],
        ),
    ]
