# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-03 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasksmanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='150x150px', upload_to='images', verbose_name='Ссылка картинки')),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='image',
        ),
        migrations.AlterField(
            model_name='task',
            name='video',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='photo',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tasksmanager.Task'),
        ),
    ]
