# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-03 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasksmanager', '0002_auto_20180103_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='task',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tasksmanager.Task'),
        ),
    ]
