# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-03 20:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasksmanager', '0003_auto_20180103_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='video',
        ),
        migrations.AddField(
            model_name='video',
            name='videokey',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='tasksmanager.Task'),
        ),
    ]
